import = [
    "~/.config/alacritty/themes/nord.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Block"

[debug]
log_level = "warn"
persistent_logging = false

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 10000
multiplier = 2

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[shell]
program = "/bin/zsh"

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = false
decorations_theme_variant = "None"
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 4

[window.position]
x = 0
y = 0
