# Jake Pauls
# https://jacobpauls.dev
# https://github.com/jacob-pauls

# Print new line at the start of prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[character]
success_symbol = "[âš¡](bold yellow)"
error_symbol = "[âš¡](bold red)"
vicmd_symbol = "[âš¡](bold green)"

[directory]
style = "bold green"
truncation_length = 1
truncate_to_repo = true
format = "[$path]($style) "

[git_branch]
style = "bold cyan"
symbol = "ğŸŒ¿ "
truncation_length = 10
truncation_symbol = ""

[git_state]
rebase = "[ğŸ“Œ REBASING](bold blue)"
merge = "[ğŸš¨ MERGING](bold yellow)"
revert = "[ğŸ”¥ REVERTING](bold yellow)"
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ’¥"
ahead = "áƒ"
behind = "á"
diverged = "â‡•"
untracked = "ğŸƒ"
stashed = "ğŸ"
modified = "ğŸ‰${count}"
staged = "ğŸ“${count}"
renamed = "ğŸ“${count}"
deleted = "âŒ${count}"
style = ""

[custom.yarn]
description = "Version for yarn in the working directory"
files = ["yarn.lock"]
symbol = "yarn "
style = "bold blue"
format = "v[$output]($style)"
